#!/usr/bin/env bash
set -e
#sometimes git returns strange things...this seems to clear the bad state.
git status &> /dev/null

#check for unstaged tracked files
if ! git diff-files --quiet; then
	echo 'There are uncommitted changes. Aborting.'
	exit 1
fi

#check for staged/not committed files
if ! git diff-index --quiet --cached HEAD; then
	echo 'There are uncommitted changes. Aborting.'
	exit 1
fi

lerna publish --yes

DIRS=packages/*
for f in $DIRS;
do
	if [ ! -d $f ] ; then
		continue
	fi

	(
	cd $f;

	PACKAGE_ID=`node -e "process.stdout.write((o => o.name+'@'+o.version)(require('./package.json')))"`
	PACKAGE_NAME=${PACKAGE_ID%@*}

	EXISTS=`npm view $PACKAGE_ID`
	if [ ${#EXISTS} == 0 ] ; then
		VERSIONS=`npm view . .versions --json | jq -r '.[]'`;
		for i in $VERSIONS;
		do
			if [[ "$i" == *alpha ]] ; then
				npm unpublish $PACKAGE_NAME@$i
			fi
		done
	fi
	)
done
