name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm config set '@nti:registry' 'https://npm.nextthought.com'
    - name: Test
      run: npm it
    - name: Lint
      run: npm run check --if-present

    # TODO: Setup code coverage/test result reporting?
    # TODO: Publish Docs?
